/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni_module2_Module2 */

#ifndef _Included_com_example_hellojni_module2_Module2
#define _Included_com_example_hellojni_module2_Module2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni_module2_Module2
 * Method:    addNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_module2_Module2_addNative
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_hellojni_module2_Module2
 * Method:    subNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_hellojni_module2_Module2_subNative
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
